SCRIPT_NAME=test.sh
cp $1 $SCRIPT_NAME
run_no_line_content=$(cat $SCRIPT_NAME | grep 'run_no_prefix')
# echo $run_no_line_content
run_no_line_content=$(echo "$run_no_line_content" | sed 's/\\/\\\\/g')
# echo $run_no_line_content
sed -i 's/'"$run_no_line_content"'/\t--run_no_prefix=\$2_test \\\n\t--test_mode=True \\\n\t--saved_model=$OPENAI_LOGDIR\/$1\/$2\/model \\\n\t--monitor=False \\\n/g' $SCRIPT_NAME

echo "# this file was autogenerated by running create_test.sh $1" >> $SCRIPT_NAME